Chore@add report mail
sparcs-kaist/otlplus-web pull request #31
Opened 2024-01-24 13:49 UTC by useruseruse

(한국어)
![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/15f6c934-b72c-496e-bbcb-ffa689117328)
(영어)
![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/1462bbac-b0e8-40fe-a056-2c1f4c2574a2)

2024-04-24 06:40 UTC, yumincho commented on src/components/blocks/ReviewBlock.jsx
> +    const parmas = {
오타인 것 같아서 수정하면 좋을 것 같습니다! line 68도 같이요 👀 
```suggestion
    const params = {
```

2024-04-24 11:41 UTC, sboh1214 requested changes

2024-04-24 11:41 UTC, sboh1214 commented on src/translations/translation.en.json
> +      "footer": "\n[Review Information]\n*This information has been filled automatically. Please do NOT edit.",
번역을 위한 string은 최대한 간결하게 유지하면 좋을 것 같습니다.
제일 앞에 붙은 \n 을 코드로 옮겨주세요 :)

2024-04-24 12:52 UTC, useruseruse commented on src/translations/translation.en.json
> +      "footer": "\n[Review Information]\n*This information has been filled automatically. Please do NOT edit.",
수정 완료했습니다..! \n 을 아예 없애는게 첨부한 이미지와 같아서 그냥 없앴습니다..

2024-05-12 14:10 UTC, sboh1214 approved these changes
now LGTM~

2024-05-12 14:11 UTC, merged