Prepare for migration
sparcs-kaist/otlplus-web pull request #49
Opened 2024-03-14 06:09 UTC by yumincho

## Description

24/03/13 회의에서 논의한 대로, block을 포함한 component들을 이전하기 위한 사전 작업을 진행합니다.

## Checklist

- [ ] tsconfig.json에서 `noImplicitAny` 옵션을 `true`로 지정합니다.
- [ ] i18n 사용을 위한 `useTranslatedString` custom hook을 생성합니다.
- [ ] index.jsx을 index.tsx로 변경합니다. (이때 `AxiosRequestConfig`에 react-ga4를 위한 metadata를 추가합니다.)

2024-03-14 15:09 UTC, sboh1214 requested changes
useTranslatedString 상당히 인상깊게 봤습니다
잘 작동하는지는 한번 테스트해보셨는지 확인차 여쭤봅니다 :)

2024-03-14 15:09 UTC, sboh1214 commented on src/index.tsx
> +            .locale(lng ?? '')
nullable fallback을 '' 빈 스트링보다는 'ko'나 'en'으로 지정해 주면 더 좋을 듯 합니다

2024-03-14 15:09 UTC, sboh1214 commented on src/index.tsx
> +      response.config.metadata.endTime.getTime() - response.config.metadata.startTime!.getTime();
endTime은 ! 연산자가 필요없는데, startTime은 ! 연산자가 필요한 이유가 있나요?
! 연산자도 지양하면 좋긴 합니다.
아래 newline도 한번 확인 부탁드려요

2024-03-14 15:09 UTC, sboh1214 commented on src/index.tsx
>  import ReactDOM from 'react-dom/client';
import React from 'react';

unused import 확인해 주세요

2024-03-14 15:09 UTC, sboh1214 commented on src/index.tsx
> +const container: HTMLElement | null = document.getElementById('root');
HTMLElement | null

이건 어차피 getElementById의 return type으로 자동 추론되니까 redundant한것 같아요

2024-03-17 09:35 UTC, yumincho commented on src/index.tsx
> +            .locale(lng ?? '')
language setting이 undefined일 경우 korean으로 지정하도록 하겠습니다!

2024-03-17 09:42 UTC, yumincho commented on src/index.tsx
> +      response.config.metadata.endTime.getTime() - response.config.metadata.startTime!.getTime();
startTime(line 75)은 **request**를 보낼 때, endTime(line 77)과 duration(line 88)은 **response**가 온 다음에 지정해 주고 있습니다. 그래서 duration 계산 시 startTime이 undefined일 가능성이 전혀 없음에도 있다고 뜨는 것 같습니다. ! 연산자를 사용해서 처리하는 대신 앞에 조건문 걸어 두는 게 나을까요?

2024-03-17 09:43 UTC, yumincho commented on src/index.tsx
> +      response.config.metadata.endTime.getTime() - response.config.metadata.startTime!.getTime();
newline은 보이면 다 없애겠습니다 🫡

2024-03-17 09:49 UTC, sboh1214 approved these changes

2024-03-17 09:50 UTC, merged