Migrate course and project related blocks
sparcs-kaist/otlplus-web pull request #50
Opened 2024-03-17 11:48 UTC by yumincho

## Description
`@/components/blocks` 중 4개 block을 `.tsx`로 전환하면서 다음 작업을 진행했습니다.
- prop-types을 제거하고 interface를 도입했습니다.
- type annotation이 필요한 경우 추가했습니다.
- i18n 중 일부를 `useTranslatedString` hook을 사용하는 것으로 변경했습니다.
- docstring을 추가했습니다.

## Checklist
- [x] CourseBlock.tsx
- [x] CourseSimpleBlock.tsx
- [x] PlannerCourseBlock.tsx
- [x] ProjectBlock.tsx

2024-03-19 07:04 UTC, useruseruse commented
먼저 PR 올려주셔서 작업하는데 참고하고 있습니다! 혹시 custom translation hook 이 필요한 부분이 아닌 다른 부분에서 useTranslation hook 이 아니라 withTranslation HOC 을 사용한 이유가 있는지 궁금합니다!

2024-03-19 14:56 UTC, yumincho commented on src/components/blocks/CourseSimpleBlock.tsx
> +export default withTranslation()(React.memo(CourseSimpleBlock));
@useruseruse 이 부분을 말씀하신 거라면 원래부터 `withTranslation()`을 사용하고 있어서 변경하지 않았습니다. 다른 부분을 말씀하신 거라면 혹시 인용해서 좀 더 자세히 설명해주실 수 있나요?

2024-03-20 05:01 UTC, sboh1214 commented on src/components/blocks/CourseBlock.tsx
>  import { appBoundClassNames as classNames } from '../../common/boundClassNames';
절대경로 추천

2024-03-20 05:02 UTC, sboh1214 commented on src/components/blocks/CourseBlock.tsx
>    const handleMouseOver = onMouseOver
이거 옆동네에서도 추천했는데, 아래처럼 간략하게 어때유?

const handleMouseOut = onMouseOut && (() => onMouseOut(course));

2024-03-20 05:04 UTC, sboh1214 commented on src/components/blocks/CourseBlock.tsx
> +              course,
prettier가 이 줄들만 newline으로 잡나요?

2024-03-20 05:05 UTC, sboh1214 commented on src/components/blocks/CourseSimpleBlock.tsx
> + * Component `CourseSimpleBlock` displays a brief overview of a course within the `CourseRelatedCoursesSubSection` on the `DictionaryPage`.
이거 한글로 적을지 영어로 적을지 팀 내에서 협의가 필요할 것 같아요

2024-03-20 05:05 UTC, sboh1214 commented on src/components/blocks/PlannerCourseBlock.tsx
> +            course,
동일한 궁금증

2024-03-20 05:06 UTC, sboh1214 commented on src/components/blocks/PlannerCourseBlock.tsx
> +    ? () => {
동일한 제안

2024-03-20 05:06 UTC, sboh1214 commented on src/components/blocks/ProjectBlock.tsx
> +    ? () => {
동일한 제안

2024-03-20 05:06 UTC, sboh1214 requested changes
몇가지 제안 해보았습니다~ :)

2024-03-20 05:12 UTC, yumincho commented on src/components/blocks/CourseBlock.tsx
> +              course,
넹.. 그렇더라고요

2024-03-20 05:45 UTC, yumincho commented on src/components/blocks/CourseBlock.tsx
>    const handleMouseOver = onMouseOver
@injoonH 가 추천해줬는데 더 간단하게 아래처럼은 어떨까요

```typescript
const handleMouseOver = () => onMouseOver?.(course);
```

이 정도면 바로 넣어줘도 될 것 같기도
```typescript
<Link
  ...
  onMouseOver={() => onMouseOver?.(course)}
  ...
>
```

2024-03-25 16:02 UTC, sboh1214 approved these changes
LGTM

2024-03-25 16:03 UTC, merged