Migrate tiles
sparcs-kaist/otlplus-web pull request #51
Opened 2024-03-19 15:21 UTC by jooyeongmee

### Description

작업 내용:

1. @/components/tiles 하위 컴포넌트 .tsx 로 전환
2. 기존의 i18n.t 사용하던 부분을 useTranslatedString 사용하도록 변경
3. 컴포넌트 내에서 사용된 utils 함수들 ts 파일 만들어서 기존의 함수 마이그레이션
4. 컴포넌트가 사용된 위치 파악하면서 해당 컴포넌트 설명 주석 추가

### Checklist
 
- [x] HorizontalTimetableTile.tsx
- [x] PlannerTile.tsx
- [x]  TimetableDragTile.tsx
- [x] TimetableTile.tsx

2024-03-19 15:26 UTC, jooyeongmee commented on src/components/tiles/HorizontalTimetableTile.tsx
> +      <div className={classNames('tile--horizonatal-timetable__content')}>
여기 className 중 오타 있는데 수정을 해도 될까요..?_? `horizonatal` -> `horizontal `

2024-03-19 15:26 UTC, jooyeongmee commented on src/utils/lectureUtils.ts
> +  return i18n.t('ui.others.sthAndNumOtherPeople', {
이 부분은 바꿔도 될지 모르겠어서 일단 놔뒀습니다

2024-03-19 15:26 UTC, jooyeongmee commented on src/utils/itemUtils.ts
> +export const getIdOfArbitrary = (type: string, typeEn: string, department?: Department) => {
여기 함수들 파라미터 안 사용하는 것도 많은데 혹시 사용하지 않는 파라미터는 제거해도 되나요?

2024-03-20 04:11 UTC, sboh1214 requested changes

2024-03-20 04:11 UTC, sboh1214 commented on src/components/tiles/HorizontalTimetableTile.tsx
> +import { appBoundClassNames as classNames } from '../../common/boundClassNames';
절대 경로 임포트 가능할까요? (import /@)

2024-03-20 04:15 UTC, sboh1214 commented on src/components/tiles/PlannerTile.tsx
> +import { appBoundClassNames as classNames } from '../../common/boundClassNames';
상대 경로 import 한 이유가 있나요?

2024-03-20 04:16 UTC, sboh1214 commented on src/components/tiles/PlannerTile.tsx
> +  semesterIndex: 0 | 1;
0 | 1 이 어떤 걸 뜻하는지 주석이 있는것도 좋을 것 같아요

2024-03-20 04:20 UTC, sboh1214 commented on src/components/tiles/PlannerTile.tsx
> +      {item.item_type !== PlannerItemType.TAKEN ? (
삼항 연산자보다는 아래 코드들 처럼 && 연산자로 바꿔보는 건 어떨까요?

2024-03-20 04:20 UTC, sboh1214 commented on src/components/tiles/TimetableDragTile.tsx
> +import { appBoundClassNames as classNames } from '../../common/boundClassNames';
Same question

2024-03-20 04:21 UTC, sboh1214 commented on src/components/tiles/TimetableTile.tsx
> +import { TIMETABLE_START_HOUR, TIMETABLE_END_HOUR } from '../../common/constants';
same question

2024-03-20 04:24 UTC, sboh1214 commented on src/components/tiles/TimetableTile.tsx
> +  const handleMouseOver = onMouseOver
생각해보니까 이것도 삼항 연산자 대신 && 연산자로 대체 가능할 거 같긴 하네요

const handleMouseOut = onMouseOut && (() => onMouseOut(lecture));

2024-03-20 04:25 UTC, sboh1214 commented on src/components/tiles/TimetableTile.tsx
> +      {!isTemp && !isTimetableReadonly ? (
이것도 삼항 연산자 대신 && 사용해서 끝에 불필요한 null 없애면 좋을 것 같습니다

2024-03-20 04:26 UTC, sboh1214 commented on src/utils/itemUtils.ts
> +export const getIdOfArbitrary = (type: string, typeEn: string, department?: Department) => {
넵! 제거해도 괜찮을 것 같아요 :)

2024-03-20 04:29 UTC, sboh1214 commented on src/utils/lectureUtils.ts
> +  const translate = useTranslatedString();
이 함수는 컴포넌트나 hook이 아니기 때문에 useXXX 를 내부해서 사용하면 예기치 못한 동작을 할수도 있어요

2024-03-20 04:31 UTC, sboh1214 requested changes
수고하셨습니다 :)
기존 jsx파일은 삭제하시고 새 tsx 컴포넌트가 잘 작동하는지 테스트해보시고 PR 설명에 스크린샷 함께 첨부해 주시면 좋을 것 같습니다.

2024-03-20 05:22 UTC, yumincho commented on src/components/tiles/HorizontalTimetableTile.tsx
> +      <div className={classNames('tile--horizonatal-timetable__content')}>
<img width="367" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/100757008/1bbc1353-8af5-4ef9-9527-ad6eaf0e4cf7">

scss 파일 variable부터가 horizonatal로 작성되어 있군요 .. 모두 한 번에 바꿔주세요!

2024-03-20 05:24 UTC, yumincho commented on src/utils/lectureUtils.ts
> +  return i18n.t('ui.others.sthAndNumOtherPeople', {
혹시 util 함수 옮길 때 작업하신 tile에서 사용되는 함수만 작업하신 건가요?

2024-03-20 06:37 UTC, yumincho commented on src/components/tiles/TimetableTile.tsx
> +  const handleMouseOver = onMouseOver
PR #51 코멘트 같이 확인해 주세요!

2024-03-25 15:58 UTC, sboh1214 approved these changes
LGTM
아래 코드 제안드립니다 :)

onMouseOver && (() => onMouseOver(item));
onMouseOver?.(item);

2024-03-25 15:58 UTC, merged