fix review block and semester block
sparcs-kaist/otlplus-web pull request #52
Opened 2024-03-20 10:27 UTC by useruseruse

2024-03-20 11:49 UTC, useruseruse commented
기타 (PR 관련된 사항은 아님)
<img width="476" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/86822199/32ba24b6-878a-46a2-8142-44bff9558284">

Planner Page 에서 ReviewBlock 이 사용되는데 `from="Dictionary" `로 되어 있고, dictionary 로 이동이 불가능한데, 이를 수정하는 것은 어떨까요..?


![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/b5d2af0c-b9bc-4636-94f5-76ed48d9a6c4)

2024-03-25 18:58 UTC, sboh1214 requested changes
수고하셨습니다~!

2024-03-25 18:58 UTC, sboh1214 commented on src/components/blocks/ReviewBlock.tsx
> +    <RootTag className={classNames('block', 'block--review')} to={linkTo ? linkTo : ''}>
link ?? '' 로 바꾸면 더 간결할 것 같아요

2024-03-25 18:58 UTC, sboh1214 commented on src/components/blocks/ReviewWriteBlock.tsx
> +  const getScoreOptionLabel = (name: string, value: number, checkedValue: number | undefined) => {
`checkedValue: number | undefined` 대신 `checkedValue?: number` 는 어떠신가요

2024-03-25 18:58 UTC, sboh1214 commented on src/components/blocks/SemesterBlock.tsx
> +type SemesterType = Semester | 'ALL';
만약 이 타입이 다른 곳에서도 사용된다면 shapes 폴더에 저장하는 것이 좋을 것 같아요

2024-03-25 18:58 UTC, sboh1214 commented on src/components/blocks/SemesterBlock.tsx
> +  const handleClick =
`const handleClick = onClick?.(semester);` 로 줄일 수 있습니다~

2024-03-26 06:17 UTC, sboh1214 approved these changes
![image](https://github.com/sparcs-kaist/otlplus-web/assets/30364442/e8ad9d7f-e80c-4daf-a282-350c4fcb41e5)

2024-03-26 06:17 UTC, merged