Convert objects to enums
sparcs-kaist/otlplus-web pull request #58
Opened 2024-03-27 14:09 UTC by yumincho

## Description
특정 redux action 혹은 util 함수 내에서 생성되어, 여러 컴포넌트에서 재사용되고 있는 object들을 enum으로 변경하였습니다.
이는 `@/actions` 내의 redux action에 TypeSript를 도입할 때 사용됩니다.

2024-03-31 12:08 UTC, jooyeongmee requested changes

2024-03-31 12:08 UTC, jooyeongmee commented on src/shapes/enum.ts
> +  CART = 'CARAT',
여기 오타 있는 것 같아요

2024-03-31 16:59 UTC, sboh1214 requested changes
수고하셨습니다~
오타 수정 및 enum value 제거 해주시면 좋을 것 같아요

2024-03-31 16:59 UTC, sboh1214 commented on src/shapes/enum.ts
> +export const enum CourseListCode {
enum의 값을 소문자에서 대문자로 바꿔도 큰 문제는 없겠죠...?

2024-03-31 16:59 UTC, sboh1214 commented on src/shapes/enum.ts
> +  CART = 'CARAT',
아래처럼 적어주시면 될 것 같아요

```js
export const enum LectureListCode {
   SEARCH,
   BASIC,
   HUMANITY,
   CART,
}
```

2024-04-01 12:46 UTC, yumincho commented on src/shapes/enum.ts
> +  CART = 'CARAT',
@sboh1214 텍스트로 비교하는 컴포넌트들이 있는 것 같아서 string enum으로 만들었는데 다시 보니 없네요 🤔 없애겠습니다

<img width="650" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/100757008/dd1f118e-8c65-4a35-b9e4-ace06e99f5a6">

2024-04-01 12:48 UTC, yumincho commented on src/shapes/enum.ts
> +export const enum CourseListCode {
enum의 값이라는 게 `OTHERS`인가요 `CourseListCode`인가요?

2024-04-01 12:51 UTC, yumincho commented on src/shapes/enum.ts
> +export const enum CourseListCode {
`CourseListCode`의 값들(e.g., 'Search')을 말씀하신 거라면 문제 없으리라 생각됩니다. 'search'를 사용하는 곳이 없고, string이 필요한 경우에는 아래 이미지처럼 그 파일 내에서 다시 정의해서 사용하고 있습니다.

<img width="889" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/100757008/e99f0293-001c-4b4f-bce0-d9ea61777915">

string enum을 쓰면 쉽게 리팩토링할 수 있을 것 같긴 한데 일단은 위 코멘트처럼 그냥 enum으로 쓰고 나중에 하나씩 보면서 바꾸는 게 좋을 것 같아여

2024-04-01 13:05 UTC, yumincho commented on src/shapes/enum.ts
> +  CART = 'CARAT',
[bf054c6](https://github.com/sparcs-kaist/otlplus-web/pull/58/commits/bf054c676cd62fcd640652e261f15e52bd0eaf41) 에서 모두 없앴습니다 🤞

2024-04-01 14:55 UTC, sboh1214 approved these changes
좋아요~ 
나중에 PlannerItemType 도 auto numbering enum으로 바꾸면 좋을 것 같습니다~!

2024-04-01 14:56 UTC, merged