Migrate Redux action creators
sparcs-kaist/otlplus-web pull request #59
Opened 2024-03-27 14:32 UTC by yumincho

## Description
`@/actions` 내 Redux action creator들에 TypeScript를 도입했습니다.
- action type으로 사용 중인 string을 literal로 변경합니다.
  - reducer의 switch-case문에서 action.type을 잘 추론하기 위해 사용됩니다.
- 파라미터들의 타입을 지정합니다.
- action type을 모아서 export합니다.
  - reducer에서 받는 action param의 타입 지정을 위해 사용됩니다.

## Checklist
- [x] common
- [x] dictionary
- [x] planner
- [x] timetable
- [x] write-reviews

2024-03-31 10:32 UTC, useruseruse commented
나머지는 잘 정의된 것 같습니다!
![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/c387dc78-f5ea-4a68-a441-e4011937cd11)

2024-03-31 12:32 UTC, jooyeongmee requested changes

2024-03-31 12:32 UTC, jooyeongmee commented on src/actions/planner/planner.ts
> +export const DUPLICATE_PLANNER = `${BASE_STRING}DUPLICATE_PLANNER` as const;
요건 밑에 사용되는 곳이 없는 것 같은데 혹시 구현이 누락된걸까요?

2024-03-31 12:32 UTC, jooyeongmee commented on src/actions/timetable/list.ts
> +export const SET_SELECTED_LIST_CODE = `${BASE_STRING}SER_SELECTED_LIST_CODE` as const;
SER_SELECTED_LIST_CODE  오타 있는 것 같습니다.

2024-04-01 13:12 UTC, yumincho commented on src/actions/planner/itemFocus.ts
> +  | ReturnType<typeof setItemFocus>
! 어떻게 찾으셨나요 [f94122b](https://github.com/sparcs-kaist/otlplus-web/pull/59/commits/f94122b601708af529bf17c8fe9a545cb734b550)에서 추가했습니다 👍

2024-04-01 15:36 UTC, yumincho commented on src/actions/planner/planner.ts
> +export const DUPLICATE_PLANNER = `${BASE_STRING}DUPLICATE_PLANNER` as const;
나중에 reducer switch-case문에서 사용될 예정입니다

2024-04-01 15:37 UTC, yumincho commented on src/actions/timetable/list.ts
> +export const SET_SELECTED_LIST_CODE = `${BASE_STRING}SER_SELECTED_LIST_CODE` as const;
[9ace73f](https://github.com/sparcs-kaist/otlplus-web/pull/59/commits/9ace73f3a923a55a884b31958d87db0f9eeabb75)

2024-04-01 15:42 UTC, yumincho commented on src/actions/planner/planner.ts
> +export const DUPLICATE_PLANNER = `${BASE_STRING}DUPLICATE_PLANNER` as const;
[6847013](https://github.com/sparcs-kaist/otlplus-web/pull/59/commits/68470136caae4ada3698ebf00fc0eef0bc13247b)

2024-04-01 15:52 UTC, yumincho commented on src/actions/common/track.ts
> +export function setTracks(tracks: Array<GeneralTrack | AdditionalTrack>) {
혹시 아래 코드 어디있나요?? otlplus랑 otlplus-web 레포 둘다 봤는데 못 찾아서요 😢

2024-04-01 15:57 UTC, yumincho commented on src/actions/common/track.ts
> +export function setTracks(tracks: Array<GeneralTrack | AdditionalTrack>) {
[373e8c8](https://github.com/sparcs-kaist/otlplus-web/pull/59/commits/373e8c8febe89852866b0c9c4f607e50e9af9968)

(1) 남겨주신 코멘트, (2) `/otlplus/apps/graduation/views.py`의 아래 코드 참고해서 작업했습니다!

```python
class TrackListView(View):
    def get(self, request):
        result = {
            'general': [gt.to_json() for gt in GeneralTrack.objects.all().order_by('is_foreign', 'start_year', 'end_year')],
            'major': [gt.to_json() for gt in MajorTrack.objects.all().order_by('department__code', 'start_year', 'end_year')],
            'additional': [gt.to_json() for gt in AdditionalTrack.objects.all().order_by(Length('type'), 'department__code', 'start_year', 'end_year')],
        }
        return JsonResponse(result, safe=False)
```

2024-04-08 14:20 UTC, sboh1214 approved these changes
ESLint prefer-template rule을 비활성화하던 주석을 제거하였습니다. 수고하셨어요 :)

2024-04-08 14:21 UTC, merged