Migration@reducers/timetable
sparcs-kaist/otlplus-web pull request #61
Opened 2024-04-06 05:04 UTC by yumincho

## ⚠️  Warning
`migration@actions` 브랜치 머지한 후에 merge할 것

## Description

### [1] lists.ts - Timetable 페이지의 검색 결과를 보여줄 때 사용

![image](https://github.com/sparcs-kaist/otlplus-web/assets/100757008/24ace48e-29fe-4a75-be85-a7d9941c5f55)
redux devtool로 확인 후 initial state의 기존 null 값들 empty array로 변경

2024-04-09 05:26 UTC, jooyeongmee requested changes

2024-04-09 05:26 UTC, jooyeongmee commented on src/reducers/timetable/lectureFocus.ts
> +  lecture: Lecture | null;
궁금해서 질문드립니다! 
혹시 요거 `lecture?: Lecture` 로 하면 안되는건가요?

2024-04-09 05:26 UTC, jooyeongmee commented on src/reducers/timetable/list.ts
> +      lectureGroups: [], // show empty array by default for search, instead of null
마이너하긴 한데 저희 이제 주석 다 영어로 다는걸로 통일하는건가요?_?

2024-04-09 05:26 UTC, jooyeongmee commented on src/reducers/timetable/timetable.ts
>        return Object.assign({}, state, {
요런것도 그냥 `return {...state, selectedTimetable: action.timetable}` 하면 보기 더 편할 것 같은데 어떻게 생각하시나요?

2024-04-14 06:27 UTC, yumincho commented on src/reducers/timetable/list.ts
> +      lectureGroups: [], // show empty array by default for search, instead of null
주석은 한국어랑 영어 중에 편하신 언어로 쓰시면 될 것 같습니다!

2024-04-14 06:33 UTC, yumincho commented on src/reducers/timetable/timetable.ts
>        return Object.assign({}, state, {
새로운 객체를 반환하는 거라 이 편이 더 간결할 것 같습니다! 바꿔서 푸시하겠습니다 👍

2024-04-14 06:45 UTC, yumincho commented on src/reducers/timetable/timetable.ts
>        return Object.assign({}, state, {
[4336a16](https://github.com/sparcs-kaist/otlplus-web/pull/61/commits/4336a1665f1b88883a1bc43e1447907b7c644a43)

2024-04-14 06:50 UTC, yumincho commented on src/reducers/timetable/lectureFocus.ts
> +  lecture: Lecture | null;
다른 컴포넌트에서 `lecture`에 `null`을 담아서 내려주는 경우가 있어서 타입에 `null`을 포함하게 되었습니다. `null`이 의미를 가지고  있을 때가 있어서 (여기서는 "아무 lecture도 focus되지 않음"을 의미) 어떻게 바꾸면 좋을지.. 🤔 나중에 컴포넌트 쪽 리팩토링하면서 다시 보게 될 것 같은데 아이디어 있으시면 공유 부탁드립니다!

2024-04-15 14:43 UTC, jooyeongmee commented on src/reducers/timetable/lectureFocus.ts
> +  lecture: Lecture | null;
엄.. 작업량이 커질 수도 있을거 같긴 한데  lecture?: Lecture 로 하고 기존에 lecture에 null을 담아서 내려주는 경우에는 lecture를 아예 안 주면 되지 않을까 생각했습니다.

2024-04-15 14:49 UTC, jooyeongmee requested changes

2024-04-15 14:49 UTC, jooyeongmee commented on src/reducers/timetable/timetable.ts
>        return Object.assign({}, state, {
여기 하나 더 있습니다! 통일하는 것이 좋을 것 같아서요

2024-04-16 02:28 UTC, yumincho commented on src/reducers/timetable/timetable.ts
>        return Object.assign({}, state, {
감사합니다! 👍  [fdf99f6](https://github.com/sparcs-kaist/otlplus-web/pull/61/commits/fdf99f6e73281d499348c02864c74a452b948016)

2024-04-16 05:03 UTC, yumincho commented on src/reducers/timetable/lectureFocus.ts
> +  lecture: Lecture | null;
말씀해주신 것처럼 불필요한 값들은 아예 안 내려주는 게 (장기적으로도) 맞는 것 같습니다. 다만 optional로 바꿔서 undefined인지 체크하는 대신 interface를 여러 개로 나눈 다음 union type으로 쓰는 건 어떤가요? 그럼 각 state에 어떤 값들이 define되어 있어야 하고, 각 값이 어떤 걸 나타내는지 명확하게 보일 것 같아요. 아래는 예시입니다!

```typescript
interface NoLectureFocusedOrClicked {
  from: LectureFocusFrom.NONE;
  clicked: false;
}

interface SingleLectureFocused {
  from: LectureFocusFrom.LIST | LectureFocusFrom.TABLE;
  clicked: false;
  lecture: Lecture;
}

interface SingleLectureClicked {
  from: LectureFocusFrom.LIST | LectureFocusFrom.TABLE;
  clicked: true;
  lecture: Lecture;
  reviews: Review[];
}

interface MultipleLectureFocused {
  from: LectureFocusFrom.MULTIPLE;
  multipleTitle: string;
  multipleDetails: Detail[];
}

type LectureFocusState =
  | SingleLectureFocused
  | SingleLectureClicked
  | MultipleLectureFocused
  | NoLectureFocusedOrClicked;

const initialState: LectureFocusState = {
  from: LectureFocusFrom.NONE,
  clicked: false,
};
```

2024-04-16 06:09 UTC, yumincho commented on src/reducers/timetable/lectureFocus.ts
> +  lecture: Lecture | null;
있던 property를 없애는 거라 다른 페이지들에서 에러가 엄청 나긴 하네요 😅 `lectureFocus`의 state를 위쪽처럼 바꾸고 reducer도 적용해줬더니 `LectureDetailSection`에서 무수한 에러가..
<img width="633" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/100757008/f36eabbc-312f-4a92-8c36-d106bf0115be">

2024-04-16 06:15 UTC, yumincho commented on src/reducers/timetable/lectureFocus.ts
> +  lecture: Lecture | null;
하지만 interface 쪼개면서 reducer 쪽도 선언적으로 같이 바꿔주면 좋을 것 같은데, 이 부분은 슬랙 채널에서 더 말씀드리겠습니다!

```typescript
const lectureFocus = (state: LectureFocusState = initialState, action: LectureFocusAction) => {
  switch (action.type) {
    ...
    case SET_LECTURE_FOCUS: {
      const shouldResetReviews =
        state.from === LectureFocusFrom.NONE ||
        ((state.from === LectureFocusFrom.LIST || state.from === LectureFocusFrom.TABLE) &&
          state.lecture.id !== action.lecture.id);

      return state.from === LectureFocusFrom.MULTIPLE
        ? state
        : {
            from: action.from,
            clicked: action.clicked,
            lecture: action.lecture,
            reviews: shouldResetReviews ? [] : state.reviews,
          };
    }
```

2024-04-22 11:17 UTC, yumincho commented on src/reducers/timetable/lectureFocus.ts
> +  lecture: Lecture | null;
interface를 쪼개거나 optional로 변경할 경우 컴포넌트 단도 함께 변경해줘야 해서 태스크 크기가 너무 커지네요. [슬랙](https://sparcs.slack.com/archives/C05PYLLLHEE/p1713257614468589)에서 말씀드린 것처럼 일단은 기존처럼 `Lecture | null`로 그대로 두겠습니다.

2024-04-22 18:08 UTC, sboh1214 commented on src/reducers/timetable/list.ts
> -      newState.lists = { ...newState.lists };
deep copy를 위해 필요한 과정이에요~

> Spread syntax effectively goes one level deep while copying an array.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2024-04-22 18:08 UTC, sboh1214 commented on src/reducers/timetable/list.ts
> -      newState.lists = { ...newState.lists };
마찬가지로 삭제하면 안됩니다 :)

2024-04-22 18:09 UTC, sboh1214 commented on src/reducers/timetable/list.ts
> -      newState.lists[LectureListCode.CART] = { ...newState.lists[LectureListCode.CART] };
마찬가지로 복구해 주세요 :)

2024-04-22 18:18 UTC, sboh1214 commented on src/reducers/timetable/timetable.ts
> -        lectures: action.timetable.lectures.slice(),
`.slice()`을 스프레드 연산자로 변경해야 할 것 같아요.

> slice()는 원본을 대체하지 않습니다. 원본 배열에서 요소의 얕은 복사본을 반환합니다. 원본 배열의 요소는 다음과 같이 반환 된 배열에 복사됩니다:
>
> 객체 참조(및 실제 객체가 아님)의 경우, slice()는 객체 참조를 새 배열로 복사합니다. 원본 배열과 새 배열은 모두 동일한 객체를 참조합니다. 참조 된 객체가 변경되면 변경 내용은 새 배열과 원래 배열 모두에서 볼 수 있습니다.

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

2024-04-22 18:20 UTC, sboh1214 commented on src/reducers/timetable/timetable.ts
> +      const updatedTable = newTables.find((t) => t.id === state.selectedTimetable?.id);
`state.selectedTimetable.id === MY` 이 부분은 없어진 건가요?

2024-04-24 06:43 UTC, yumincho commented on src/reducers/timetable/lectureFocus.ts
> +        reviews: lectureChanged ? null : state.reviews,
`lectureChanged`일 때는 `reviews: null`을 통해 기존 값이 `null`로 바뀌는데, 바뀌지 않았다면 덮어쓰지 않고 기존 값 (`state.reviews`)를 그대로 가져가게 되기 때문에 이렇게 작성해 두었습니당

2024-04-24 06:48 UTC, yumincho commented on src/reducers/timetable/list.ts
> -      newState.lists = { ...newState.lists };
(수정 전) line 86에서 deep copy가 됐고, (수정 전) line 89에서 deep copy된 object의 값을 바로 바꿔주고 있어서 삭제해도 되는 코드라고 생각했는데 제가 놓친 부분이 있을까요? 🤔

2024-04-24 06:53 UTC, yumincho commented on src/reducers/timetable/list.ts
> -    if (lectures.length === 0) {
조기 종료를 위한 코드고, 아래쪽 로직을 그대로 따라 갔을 때에도 동일하게 empty array가 반환되고 있어서 제거했습니다.
```typescript
  const groupLectures = (lectures: Lecture[]) => {
    ...
    console.log('lectures:', lectures, 'lectureGroups:', lectureGroups);
    return lectureGroups;
```
<img width="284" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/100757008/b3d1e149-d4c6-49f0-932a-c9ea0223cedc">

2024-04-24 06:58 UTC, yumincho commented on src/reducers/timetable/timetable.ts
> -        lectures: action.timetable.lectures.slice(),
state가 아니고 action의 값을 가져다 쓰는 거라 deep copy를 하지 않아도 된다고 생각했는데, action으로 넘어오는 값들이 mutable할 수도 있겠네요 😱 수정하겠습니다

2024-04-24 07:19 UTC, yumincho commented on src/reducers/timetable/timetable.ts
> +      const updatedTable = newTables.find((t) => t.id === state.selectedTimetable?.id);
위쪽에서 조기종료 해줘서 조건이 빠졌습니다. (시간표 reorder는 불가능한 경우의 수가 명확하고 + 타입 체킹에 걸려서 조기종료 해줬슴다)

```typescript
if (!state.timetables || !state.selectedTimetable || state.selectedTimetable.id === MY) {
  return state;
}
```

아래처럼 optional chaining (`?.`) 걸어줄 수도 있긴 한데 그럼 null을 return해서 문제가 되므로 ..
```typescript
 // optional chaining 예시
const newTables = state.timetables?.map((t) => { ... } // timetables 검사

newTables?.sort((t1, t2) => ... ); // newTables 검사
const updatedTable =
  state.selectedTimetable?.id === MY // selectedTimetable 검사
  ? state.selectedTimetable
  : newTables?.find((t) => t.id === state.selectedTimetable?.id); // 또 selectedTimetable 검사

return ...
```

2024-04-25 11:11 UTC, yumincho commented on src/reducers/timetable/list.ts
> -      newState.lists = { ...newState.lists };
완전 deep copy가 되는 게 아니고 참조가 복사되는군요 .. 되돌려서 커밋하겠습니당

2024-04-25 11:28 UTC, yumincho commented on src/reducers/timetable/list.ts
> -      newState.lists = { ...newState.lists };
[048b859](https://github.com/sparcs-kaist/otlplus-web/pull/61/commits/048b859ec6f2b3ef73826deb656b341d0242b419)

2024-04-25 11:28 UTC, yumincho commented on src/reducers/timetable/list.ts
> -      newState.lists = { ...newState.lists };
[048b859](https://github.com/sparcs-kaist/otlplus-web/pull/61/commits/048b859ec6f2b3ef73826deb656b341d0242b419)

2024-04-25 11:30 UTC, yumincho commented on src/reducers/timetable/list.ts
> -      newState.lists[LectureListCode.CART] = { ...newState.lists[LectureListCode.CART] };
[048b859](https://github.com/sparcs-kaist/otlplus-web/pull/61/commits/048b859ec6f2b3ef73826deb656b341d0242b419)

`newState.lists[LectureListCode.CART]` 오브젝트 하위에는 `lectureGroups` 밖에 없고, 바로 다음 줄에서 새로운 값을 할당해주기 때문에 다음 라인은 복구하지 않았습니다

```typescript
newState.lists[LectureListCode.CART] = { ...newState.lists[LectureListCode.CART] };
```

2024-04-26 03:28 UTC, merged