migrate reducer
sparcs-kaist/otlplus-web pull request #63
Opened 2024-04-26 14:00 UTC by useruseruse

변경사항 
1. `list.ts`
     - search, basic, humanity, taken 은 필수로 있고, 전공과목들도 optional 하게 key 로 추가될 수 있음. 
     - 이에 따라 enum 타입에 전공과목들을 추가하고 이를  key 로 사용함.  
        전공과목 탭을 클릭할 경우 state 의 list의 키로 해당 전공과목이 추가되며, 불러온 리스트들이 value 로 닮김.
      - dictionary 나 timetable 에서도 해당 enum 을 사용하고 있는데 동일한 구조임.
        ![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/e5ee1df2-4912-427f-85d9-9546c43db0d0)

    - courseRead 가 있는데, 실제로 사용 안하고 있어서 관련 action, reducer 부분 주석 처리함, 문제 없으면 pr 머지 전에 삭제할 예정
        (원래 dictionary 에서는 읽은 course 들의 색깔을 다르게(핑크색 → 회색)으로 바꾸는 등의 ui 변화가 있으나, planner 는 없음. )
    - `newState.lists[action.code] = { …newState.lists[action.code] }; `등과 유사한 부분은 삭제하였음.  lists 객체에 courses 밖에 필드가 없기 때문에, 나머지 필드를 복제하는 건 의미없다고 생각해서 삭제하였음. 
     ![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/445f4add-60be-4d2e-8b46-375dc48a0237)
  
 3. `planner.ts` 
    -  원래 initial state 의 planners가  null 이고 planner를 처음 불러올 때, (컴포넌트 마운팅할 때) [] 로 초기화 시켜주는데,
     초기화 시켜주는 것을 지우고 initial state 를  null 에서 Planner[] 로 변경, 
    Planners 가  null 일 필요가 없는 것으로 확인하여 type 추론에 유리하도록 변경하였음. 
  ![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/4b7b45c9-ac51-4828-bdeb-790233dc84b2)

4. `search.ts` 
    - initial state 의 start: null, end: null, day: null, 사용하지 않아서 제거하였음. 
   
5. `itemFocus.ts` 
    -   모든 ItemFocusState는   '@/shapes/state/planner/ItemFocus' 에 정의된 5가지 중 하나의 타입을 가짐. 
    `type ItemFocus = NoneItem | ListItem | AddingItem | TableItem | CategoryItem;
`
   새로운 state를 만들 때 이전의 state 를 복제하는 부분을 지우는 것이 의미적으로 맞는 것 같은데, 상태를 변경하기 전에 clear 를 통해 초기화해주므로 문제는 없는 것 같아 그대로 두었음.  (ex. category Item을 set 할 때, 이전의  ListItem 의 속성을 가지면 안되므로...) 

  <img width="445" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/86822199/cda67099-efb0-4b88-a5d1-4a985a8b483a">

2024-04-28 06:20 UTC, yumincho commented on src/actions/planner/list.ts
> +// export const ADD_COURSE_READ = `${BASE_STRING}ADD_COURSE_READ` as const;
`add_course_read`가 dictionary 쪽에도 있는 것 같은데 혹시 어떤 기능을 하나요?

2024-04-28 06:20 UTC, yumincho commented on src/reducers/planner/list.ts
> +};
사용자가 플래너 설정에서 전공 정보 변경해줄 때마다 유동적으로 이 interface를 업데이트 하는 방법은 없겠죠..? 😂

2024-04-28 06:20 UTC, yumincho commented on src/reducers/planner/list.ts
> +      };
오 spread syntax 이렇게 작성하는 게 더 간결한 것 같은데, deep copy 문제는 없는지 @sboh1214  한 번 확인해주실 수 있나요? 괜찮으면 timetable도 이 방식으로 리팩토링하면 어떤가 해서요 👀

2024-04-28 06:20 UTC, yumincho commented on src/reducers/planner/planner.ts
> +      }
요 라인 제거해도 문제 없을 것 같습니다!

2024-04-28 06:20 UTC, yumincho commented on src/reducers/planner/planner.ts
> +      const updatedPlanner = newPlanners.find((t) => t.id === state.selectedPlanner?.id);
위쪽에 if문 추가한다면 여기 optional chaining 빼는 게 어떨까요?

```suggestion
      const updatedPlanner = newPlanners.find((t) => t.id === state.selectedPlanner.id);
```

2024-04-28 08:09 UTC, useruseruse commented on src/actions/planner/list.ts
> +// export const ADD_COURSE_READ = `${BASE_STRING}ADD_COURSE_READ` as const;
![image](https://github.com/sparcs-kaist/otlplus-web/assets/86822199/c8f6927d-f2e6-46a8-890f-9022303c246a)
dictionary 에서는 위와 같이 읽은 course 는 ui 를 다르게 표시해주지만, 
<img width="286" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/86822199/a475a8d2-868b-451f-88f5-46d48077f0fd">
planner에서는 관련된 부분이 없습니당

2024-04-28 08:13 UTC, useruseruse commented on src/reducers/planner/list.ts
> +};
으음 유동적으로 변경한다는 말을 구체적으로 설명해주실 수 있나요??

2024-04-29 06:32 UTC, yumincho commented on src/actions/planner/list.ts
> +// export const ADD_COURSE_READ = `${BASE_STRING}ADD_COURSE_READ` as const;
확인했습니다! 감사해요 👍

2024-04-29 06:34 UTC, yumincho commented on src/reducers/planner/list.ts
> +};
플래너 설정에서 전공 정보를 변경하면 해당되는 사이드 탭들이 생기는 거라고 알고 있어서, 이 `CourseDepartmentLists`에 모든 `DepartmentCode`를 넣는 게 아니라 사용자마다 해당하는 값들만 키로 넣을 수 있나 했어요! 제 생각에는 방법이 없을 것 같긴 한데.. 혹시 다른 분들 중에 방법을 아시는 분이 있을까 해서 코멘트 남겨봤슴당 🤯

2024-05-10 04:15 UTC, yumincho commented on src/actions/planner/list.ts
> +// export const ADD_COURSE_READ = `${BASE_STRING}ADD_COURSE_READ` as const;
`addCourseRead` 관련 주석들도 지워주세요!

2024-05-10 04:15 UTC, yumincho commented on src/reducers/planner/list.ts
> +      };
이 코멘트는 @sboh1214 님께 확인 후 resolve 부탁드릴게요

2024-05-10 04:15 UTC, yumincho commented on src/components/sections/planner/plannerandinfos/PlannerTabs.jsx
> +      // setPlannersDispatch([]);
(그냥 코멘트) 이 부분은 일단 주석 처리해두고 넘어가고, 나중에(..) planner 쪽 컴포넌트 리팩토링할 때 재확인 후 지우면 될 것 같습니다 👍

2024-05-12 14:25 UTC, yumincho commented on src/components/sections/planner/plannerandinfos/PlannerTabs.jsx
> +      // setPlannersDispatch([]);
확인해보니 user 정보 없을 때 최초로 `[]` 세팅해줘야 해서 필요한 거였습니다 ㅇ0ㅇ 주석 처리하면 안 되네요!

```suggestion
      setPlannersDispatch([]);
```

2024-05-12 14:55 UTC, sboh1214 commented on src/reducers/planner/list.ts
> +      };
오 좋습니다~ 앞으로 요렇게 작성하면 좋을 것 같아요 :)

2024-05-12 14:59 UTC, sboh1214 commented on src/components/sections/planner/plannerandinfos/PlannerTabs.jsx
> +      // setPlannersDispatch([]);
reducers/planner/planner.ts 에서 PlannerState의 initialState를 planners: null 에서 planners: [] 로 변경해서 setPlannersDispatch([]);  코드가 필요없어졌는데,
원복하기로 결정하였습니다.

2024-05-12 15:00 UTC, sboh1214 commented on src/actions/planner/list.ts
> +// export const ADD_COURSE_READ = `${BASE_STRING}ADD_COURSE_READ` as const;
제가 대신 지웠습니다~

2024-05-12 15:12 UTC, sboh1214 requested changes
planner.ts 코드 원복합시다 @yumincho

2024-05-12 15:12 UTC, sboh1214 commented on src/reducers/planner/planner.ts
> +  planners: [],
초기값을 []에서 null로 원복하기로 결정~

2024-05-13 04:57 UTC, useruseruse commented on src/reducers/planner/planner.ts
> +  planners: Planner[];
```suggestion
  planners: Planner[] | null;
```

2024-05-13 04:57 UTC, useruseruse commented on src/components/sections/planner/plannerandinfos/PlannerTabs.jsx
> +      // setPlannersDispatch([]);
```suggestion
       setPlannersDispatch([]);
```

2024-05-13 04:57 UTC, useruseruse commented on src/reducers/planner/planner.ts
> +  planners: [],
```suggestion
  planners: null,
```

2024-05-13 16:48 UTC, sboh1214 approved these changes
![Dog LGTM Keyboard](https://media0.giphy.com/media/kbVzENVNlE60MQR1HY/giphy.gif?cid=47028fa8csl9l5acl0vpvf4ot7uyywx1iwuk64p7jcbqvj1q&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-05-13 16:49 UTC, merged