migrate: reducer dictionary
sparcs-kaist/otlplus-web pull request #64
Opened 2024-05-01 11:31 UTC by jooyeongmee

진행 상황: 

- [x] 코드 수정
- [ ] 테스트

특이 사항:
- 코드 수정 중 CourseLastSearchOption 타입이 optional 처리가 빠진 것 같아 추가하였습니다.

2024-05-03 04:37 UTC, yumincho commented on src/reducers/dictionary/courseFocus.ts
> +      const foundIndex = originalReviews?.findIndex((r) => r.id === review.id) ?? -1;
optional chaining(`?.`) 쓰는 대신 앞쪽에서 조기종료하고 기존 state 그대로 return하면 어떨까요? 그럼 (1) state에 의도하지 않은 `undefined`가 추가되는 상황을 방지할 수 있고 (2) non-null assertion operator(`!.`)도 안 쓸 수 있습니다

2024-05-03 04:37 UTC, yumincho commented on src/reducers/dictionary/list.ts
> +      courses: Course[][] | null;
`Course[]`인 걸로 알고 있는데 `Course[][]` 맞는지 재확인 부탁드립니다 :)

2024-05-08 08:05 UTC, yumincho commented on src/reducers/dictionary/courseFocus.ts
> +      if (originalReviews == undefined) {
`originalReviews`가 null일 때도 조기종료 해줘야 할 듯해서 아래처럼 작성하는 거 추천드립니다!

```suggestion
      if (!originalReviews) {
```

2024-05-08 13:12 UTC, Davidace136 approved these changes

2024-05-12 07:12 UTC, yumincho approved these changes
👍

2024-05-12 15:37 UTC, sboh1214 requested changes

2024-05-12 15:37 UTC, sboh1214 commented on src/reducers/dictionary/courseFocus.ts
> +        reviews: courseChanged ? null : state.reviews,
기존 코드에서는 courseChanged가 false일때 변경을 일으키지 않았는데,
새 코드에서는 state.reviews와 state.lectures를 할당하는 이유가 있나요?

2024-05-12 15:37 UTC, sboh1214 commented on src/shapes/state/dictionary/CourseLastSearchOption.ts
> +  term?: string[];
- optional이 추가되는 이유가 있나요?
- 다른 곳에서는  | null 을 추가했는데 여기는 undefined로 처리하는 이유가 있나요?

2024-05-12 15:37 UTC, sboh1214 commented on src/reducers/dictionary/search.ts
> +        start: null,
start, end, day는 쓰이지 않는 state 같아요

2024-05-13 11:53 UTC, jooyeongmee commented on src/reducers/dictionary/courseFocus.ts
> +        reviews: courseChanged ? null : state.reviews,
아무것도 할당하지 않는거랑 그냥 기존의 값을 그대로 주는 것이 같다고 생각되어서 이렇게 수정했는데 혹시 영향이 가는걸까요?

2024-05-13 11:53 UTC, jooyeongmee commented on src/shapes/state/dictionary/CourseLastSearchOption.ts
> +  term?: string[];
lastSearchOption: CourseLastSearchOption; 에서 lastSearchOption 의 initialState가 null이 아닌 {}으로 되어 있었는데 혹시 다른 곳이 영향이 갈가봐 일단 원래대로 두었습니다. initialState null로 하면 다시 optional 지워도 될 것 같은데 null로 갈까요?

2024-05-13 17:04 UTC, sboh1214 commented on src/reducers/dictionary/courseFocus.ts
> +        reviews: courseChanged ? null : state.reviews,
그렇긴 하네요 괜찮을 것 같습니다~

2024-05-13 17:08 UTC, sboh1214 approved these changes
![NASA LGTM](https://media2.giphy.com/media/MUKtQ1aRXwkO8ntpfg/giphy.gif?cid=47028fa8csl9l5acl0vpvf4ot7uyywx1iwuk64p7jcbqvj1q&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-05-13 17:08 UTC, merged