Set up react-query
sparcs-kaist/otlplus-web pull request #71
Opened 2024-05-16 11:35 UTC by yumincho

2024-05-16 11:47 UTC, yumincho commented
763fdfbf020dbf0fc650bffb8cbc14895f7dc2cf 커밋이 문제였네요. React를 import해주던 라인을 지우면 안 되는 거였습니다. 이 PR에서 수정해도 괜찮을까요?

2024-05-19 14:59 UTC, jooyeongmee commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +    setSelectedDepartments(selectedDepartments);
요거는 그냥 현재 state에 있는 값을 다시 setState 하는 것처럼 보이는데 뭐하는 용도인지 알 수 있을까요?

2024-05-19 14:59 UTC, jooyeongmee commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +  const departmentOptions = allDepartmentOptions
이거랑 밑에 hasChange함수에 useMemo 추가하면 어떨까요?

2024-05-19 14:59 UTC, jooyeongmee commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +      selectedDepartments: Array.from(selectedDepartments).filter((d) => d !== 'ALL'),
요거 훅에서도 selectedDepartments 받으면 이렇게 처리하던데 혹시 중복으로 처리하는 이유가 있을까요?

2024-05-19 16:20 UTC, sboh1214 requested changes
`src/components/sections/account/__tests__/AcademicInfoSubSection.test.tsx` 파일 참조하시면 단순 렌더링 테스트 뿐만 아니라, 컴포넌트에 학번과 이메일이 잘 표출되는지 테스트하고 있습니다.
확인하신 후 이런 식의 테스트를 앞으로 작성할지 동방에서 이야기 나누어보면 좋을 것 같습니다.

2024-05-19 16:20 UTC, sboh1214 commented on src/queries/account.ts
> +    queryKey: ['departmentOptions'],
이거 queryKey들을 enum으로 만들어서 관리하면 어떨까요?

2024-05-19 16:20 UTC, sboh1214 commented on src/queries/account.ts
> +    },
이거 제가 react-query를 잘 몰라서 질문하는 거긴 한데, 아래와 같이 한줄로 쓸수 있나요?

```ts
queryClient.invalidateQueries({ queryKey: ['departmentOptions', 'sessionInfo'] });
```

2024-05-23 07:55 UTC, yumincho commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +  const departmentOptions = allDepartmentOptions
`useMemo` 좋은 생각인 것 같슴당! 그런데 이렇게 써주면 return null 때문에 에러가 나요 🤯 

```typescript
  if (!user || !allDepartmentOptions) {
    return null;
  }

  const departmentOptions = useMemo(
    () =>
      allDepartmentOptions
        .flat(1)
        .map((d) => [String(d.id), `${translate(d, 'name')} (${d.code})`]),
    [allDepartmentOptions],
  );
```
<img width="599" alt="image" src="https://github.com/sparcs-kaist/otlplus-web/assets/100757008/9193fa55-4871-4e89-a5b5-827a45aacd52">

그래서? 아래처럼 순서를 바꿔서 + condition 달아서 해결하려고 했는데 뭔가 아름답지 않네용..

```typescript
  const departmentOptions = useMemo(
    () =>
      allDepartmentOptions
        ? allDepartmentOptions
            .flat(1)
            .map((d) => [String(d.id), `${translate(d, 'name')} (${d.code})`])
        : [],
    [allDepartmentOptions],
  );

  if (!user || !allDepartmentOptions) {
    return null;
  }
```

아예 요 후처리를 query 쪽에서 해서 넘겨주는 걸로 바꿔보겠습니당

2024-05-23 08:27 UTC, yumincho commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +  const departmentOptions = allDepartmentOptions
`hasChange`는 사용자가 department option 선택/해제 할 때마다 바뀌는지 체크하는 로직이라 useMemo 안 써도 될 듯합니닷

2024-05-23 08:46 UTC, yumincho commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +    setSelectedDepartments(selectedDepartments);
[3e1868d](https://github.com/sparcs-kaist/otlplus-web/pull/71/commits/3e1868d5942059ca6fe7bcf48a5927a1e733a9ba)

2024-05-23 08:46 UTC, yumincho commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +  const departmentOptions = allDepartmentOptions
[1115a90](https://github.com/sparcs-kaist/otlplus-web/pull/71/commits/1115a90c11035e405f5dde0bb126b37efd642909)

2024-05-23 08:49 UTC, yumincho commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +      selectedDepartments: Array.from(selectedDepartments).filter((d) => d !== 'ALL'),
오 아니요 실수입니닷 .. 수정하겠습니다 👍

2024-05-23 08:52 UTC, yumincho commented on src/queries/account.ts
> +    queryKey: ['departmentOptions'],
좋아요 👍 페이지 별로 api를 분리하고 있고 페이지 간에 서로 invalidate하는 경우는 거의 없을 것 같아서, 우선은 각 페이지 최상단에 정의해 두겠습니다

2024-05-23 08:52 UTC, yumincho commented on src/queries/account.ts
> +    },
저게 OR 연산자가 아니라 AND 연산자라 저렇게 하면 저 두 queryKey를 다 가지고 있는 쿼리만 invalidate됩니다! 그래서 각각 한 줄로 작성했어요 😂

2024-05-23 10:46 UTC, yumincho commented on src/components/sections/account/FavoriteDepartmentsSubSection.tsx
> +      selectedDepartments: Array.from(selectedDepartments).filter((d) => d !== 'ALL'),
[c5c1b2c](https://github.com/sparcs-kaist/otlplus-web/pull/71/commits/c5c1b2c6585fcee4f2317a4102d938fd197629ec)

2024-05-23 10:52 UTC, yumincho commented on src/queries/account.ts
> +    queryKey: ['departmentOptions'],
[96649d9](https://github.com/sparcs-kaist/otlplus-web/pull/71/commits/96649d948968ad2fb536a5a3f6286f3ae301e865)

2024-05-27 15:43 UTC, jooyeongmee commented
migration 브랜치와 비교해봤을 때 마이페이지에서 설정 부분 텍스트가 로딩 시 사라지는 것 같습니다.
기존 브랜치: 로딩 시 설정 텍스트가 나옴

https://github.com/sparcs-kaist/otlplus-web/assets/89931104/8a7e1615-6bcb-47b3-8fcd-57d9db0ee8da

현재 브랜치: 로딩 시 설정 텍스트 안 나옴

https://github.com/sparcs-kaist/otlplus-web/assets/89931104/a59ae943-770c-4256-a594-fc720c419ecc


그리고 개인적인 의견인데 화면녹화 해보니 설정 부분 데이터 나오는 과정이 상당히 오래 걸리는데(약 15초) 혹시 로딩 시 로딩뷰(?)를 넣는 건 어떨까요?

2024-05-30 05:30 UTC, yumincho commented
@jooyeongmee 지적 감사합니다. 수정했어요! [bc0afd0](https://github.com/sparcs-kaist/otlplus-web/pull/71/commits/bc0afd064b7b2066cf24c50e81795714c6553ec1)

https://github.com/sparcs-kaist/otlplus-web/assets/100757008/8f1003e2-4113-42c2-88f6-b3e38835bdd2

2024-05-30 05:46 UTC, jooyeongmee approved these changes

2024-06-01 08:26 UTC, sboh1214 approved these changes
![NASA LGTM](https://media2.giphy.com/media/MUKtQ1aRXwkO8ntpfg/giphy.gif?cid=47028fa8csl9l5acl0vpvf4ot7uyywx1iwuk64p7jcbqvj1q&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-06-01 08:27 UTC, merged