Set up redux root
sparcs-kaist/otlplus-web pull request #72
Opened 2024-05-18 14:14 UTC by yumincho

## Description

Redux의 root reducer를 생성해 root state를 export함으로써, 컴포넌트에서 사용하는 redux state에 타입을 명시할 수 있도록 합니다.

## Notes

-  reducer에 return type 적용
- `@/reducers/planner/itemFocus.ts`에 explicit type casting 추가

```typescript
  case CLEAR_ITEM_FOCUS: {
    return {
      ...
    } as NoneItem; // use `as` keyword
  }
```

2024-05-23 00:07 UTC, sboh1214 requested changes
정말 많은 파일들에 변화가 있었는데 너무 수고 많으셨습니다!

src/shapes/state/planner/ItemFocus.ts 에서는 기존 타입에 문제가 있었는데, 리뷰 과정에서 잡아내지 못한 것이 아쉽네요 ㅠㅜ
src/App.tsx 나 src/index.tsx 는 다같이 리뷰하면 좋을 것 같습니다 :)

2024-05-23 00:07 UTC, sboh1214 commented on src/const.ts
> +export const CAMPAIGN_KEY = 'CMPGN-2023-08-24-v1';
요거는 날짜가 들어가 있는 키인 것 같은데, 어떻게 작동하는 방식인지 설명 부탁드릴 수 있을까요?

2024-05-23 00:07 UTC, sboh1214 commented on src/redux/index.ts
> +import dictionaryReducer from '@/redux/reducers/dictionary/index';
import 구문 쪽이라서 크게 가독성을 헤치진 않지만, index는 생략해도 될거에요~ Just FYI

`import dictionaryReducer from '@/redux/reducers/dictionary';`

2024-05-27 07:06 UTC, yumincho commented on src/App.tsx
> +      .then((response) => {
Promise 다루는 것들은 then catch 쓰고 아닌 것들은 try catch 쓰면 될 것 같은데, 나중에 논의할 수 있도록 노션 아젠다에 기록해두겠습니당~ 이번 PR에는 관련해서 바꾼 부분이 (아마도) 없을 거라 수정 없이 resolve 할게용

2024-05-27 07:08 UTC, yumincho commented on src/App.tsx
> +                category: 'Campaign',
오 좋아요 이건 [노션 백로그](https://www.notion.so/sparcs/c0b4aef895c2450b94b6e0738e25abf4?v=a7c2006c852d4b379aa5da6d08f9352a&pvs=4)에 작성해두겠습니당

2024-05-27 07:08 UTC, yumincho commented on src/components/sections/account/FavoriteDepartmentsSubSection.jsx
> +import { setUser } from '../../../redux/actions/common/user';
아뇨 제가 놓쳤습니다 ^^... 고칠게요!

2024-05-27 07:12 UTC, yumincho commented on src/redux/index.ts
> +import dictionaryReducer from '@/redux/reducers/dictionary/index';
오 그렇군 그럼 지워두겠슴당 🙏

2024-05-27 07:16 UTC, yumincho commented on src/const.ts
> +export const CAMPAIGN_KEY = 'CMPGN-2023-08-24-v1';
@UrWrstNightmare 의 예전 배너 작업과 관련되어 있을 거예요. 로직은 자세히 안 보고 따로 const로 빼기만 해서 작동 방식은 잘 모릅니다 .. 🙄

2024-05-27 07:25 UTC, yumincho commented on src/redux/index.ts
> +import dictionaryReducer from '@/redux/reducers/dictionary/index';
[54b4f9c](https://github.com/sparcs-kaist/otlplus-web/pull/72/commits/54b4f9cecc08735e038500f9f4f4454998a38045)

2024-05-27 07:26 UTC, yumincho commented on src/App.tsx
> +        <BannerPopup popupOpen={popupOpen} setPopupOpen={(state) => setPopupOpen(state)}>
[54b4f9c](https://github.com/sparcs-kaist/otlplus-web/pull/72/commits/54b4f9cecc08735e038500f9f4f4454998a38045)

2024-05-27 07:26 UTC, yumincho commented on src/App.tsx
> +  const [popupOpen, setPopupOpen] = React.useState(
[54b4f9c](https://github.com/sparcs-kaist/otlplus-web/pull/72/commits/54b4f9cecc08735e038500f9f4f4454998a38045)

2024-05-27 15:38 UTC, sboh1214 approved these changes
![Simon Thumbs](https://media2.giphy.com/media/paYMkqI9PFkVSKcSuN/giphy.gif?cid=47028fa8csl9l5acl0vpvf4ot7uyywx1iwuk64p7jcbqvj1q&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-05-27 15:38 UTC, merged